### ISSUE TITLE
error in example callback

### ISSUE THREAD

**Issue by darshangiri06** [nicknochnack/LipNet#1]
numpyiterator object has no attribute as_numpy_iterator

![error_lipnet](https://user-images.githubusercontent.com/124483904/216804974-7a462905-e33b-437b-9e36-e93487756d67.jpg)

**Comment by yogeshkendre** [comment]
same issue here

**Comment by yogeshkendre** [comment]
> numpyiterator object has no attribute as_numpy_iterator

example_callback = ProduceExample(data) instead test
pass data instead of test

**Comment by Kshitij-200** [comment]
Bro you saved the day 😀
![RightHighfiveGIF](https://user-images.githubusercontent.com/93885290/222237630-d7b09508-e029-47be-89bc-f60489619c92.gif)

**Comment by nicknochnack** [comment]
My bad, realised I overwrote the test partition with an example. I've updated the notebook, all fixed guys!
