### ISSUE TITLE
'test' object has no attribute 'as_numpy_iterator'

### ISSUE THREAD

**Issue by ammaarkhan** [nicknochnack/LipNet#2]
Error when predicting on test data.
<img width="835" alt="Screen Shot 2023-02-20 at 6 30 21 PM" src="https://user-images.githubusercontent.com/98288912/220232611-238ed4b3-c933-4401-9c00-13d90ad6ff06.png">

**Comment by nicknochnack** [comment]
Fixed, give it a crack now. The test partition was overwritten during prototyping. New notebook is up!
