### ISSUE TITLE
'_NumpyIterator' object has no attribute 'as_numpy_iterator'

### ISSUE THREAD

**Issue by Kshitij-200** [nicknochnack/LipNet#3]
![Screenshot 2023-03-02 000829](https://user-images.githubusercontent.com/93885290/222234136-e21b437e-ad1e-4004-8ff5-d6bd9948e1a8.png)

**Comment by Kshitij-200** [comment]
Anyone can help.

**Comment by niquejoe** [comment]
Im having the same error and issue, any luck in solving it?

**Comment by nicknochnack** [comment]
Fixed, give it a crack now. The test partition was overwritten during prototyping. New notebook is up!

**Comment by Kshitij-200** [comment]
Thank you sir

**Comment by niquejoe** [comment]
That solved it. thanks!
