### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/alignments/s1/.align'

### ISSUE THREAD

**Issue by puranjay123** [nicknochnack/LipNet#4]
While running this code cell `data.as_numpy_iterator().next()` i am receiving this error. It is going in the alignments folder but the location is in s1 folder as mentioned in this code
`
data = tf.data.Dataset.list_files('./data/s1/*.mpg')
`
I am using google collab and I am not using `gdown.extractall('data.zip')`
instead, I am using this line of code to unzip the file
`!unzip -q "/content/drive/MyDrive/data.zip"` 
 This is changing the folder's file path and causing this error.

Here is the full error I am receiving:
`
UnknownError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} FileNotFoundError: [Errno 2] No such file or directory: 'data/alignments/s1/data/s1/pgay3a.align'
Traceback (most recent call last):

  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/ops/script_ops.py", line 269, in __call__
    return func(device, token, args)

  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    outputs = self._call(device, args)

  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/ops/script_ops.py", line 154, in _call
    ret = self._func(*args)

  File "/usr/local/lib/python3.9/dist-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "<ipython-input-15-b01e7b77d0eb>", line 8, in load_data
    alignments = load_alignments(alignment_path)

  File "<ipython-input-14-61ba78e7e7b4>", line 2, in load_alignments
    with open(path,'r') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'data/alignments/s1/data/s1/pgay3a.align'

	 [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]
`

**Comment by natapuskareva** [comment]
![image](https://user-images.githubusercontent.com/126642210/235833948-4057c76d-3cef-4257-8309-36dfaa0dc9e6.png)
Hi, I have the same issue. Do you know how to solve it?

**Comment by puranjay123** [comment]
hi @natapuskareva 
I have found the solution and I have updated the code in this repository
https://github.com/puranjay123/100_Days_of_MachineLearning/blob/main/Research%20paper%20%20Implementation/LipNet%20End-to-End%20Sentence-level%20Lipreading/lip_sync%20(1).ipynb
